# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Weiwei's Tech Blog
name: Weiwei's Tech Blog
description: 
  This is a Tech blog of Weiwei, who is a curious person enjoying figuring out the building blocks of the world, and rearranging them to build something even better. Currently I'm a master of CS student, I believe my career is developing software, and my life is adventuring.
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  cao-weiwei

# jekyll-paginate configuration
paginate: 10

# Build settings
markdown: kramdown
toc_levels: 1..6
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: ["_pages"]
permalink: /posts/:title/
excerpt_separator: <!--more-->
# author: https://www.linkedin.com/in/weiwei-cao/

host: 0.0.0.0

