# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'weiwei'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: 'UA-91332049-1'

menu: 
  - name: Projects
    submenu:
      - name: SnakeGame
        link: https://github.com/cao-weiwei/Snake_Game_Python
      - name: SearchEngine
        link: https://github.com/cao-weiwei/WahSearch
      - name: TwitterSentimentAnaylsis
        link: https://github.com/cao-weiwei/SESentimentAnaylsis
      - name: ChinaTrainTicketsCralwer
        link: https://github.com/cao-weiwei/12306query-tickets
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/cao-weiwei
      - name: LinkedIn
        icon: linkedin-square
        link: http://www.linkedin.com/in/weiwei-cao/
#       - name: Twitter
#         icon: twitter
#         link: https://twitter.com/koint
    
